openapi: 3.0.0
info:
  title: Watershed (cuHacking 2021)
  version: 0.2
  description: The Backend API for Watershed (cuHacking 2021)
  license: 
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Authentication
  - name: Users
  